### ISSUE TITLE
Use outside of nodejs

### ISSUE THREAD

**Issue by mtygesen** [matiasvlevi/easy-mnist#1]
Would it be possible to use this library client side via. url?

**Comment by matiasvlevi** [comment]
It would be possible.
Would it be the right thing to do? No.

This library loads X number of `mnist` samples in the system's Heap.

What you are looking for is a node.js server which serves an individual mnist sample to your web application through http.
Your page would load for eternity trying to load the entire dataset in the browser.

You could use [express.js](https://expressjs.com/) to serve individual mnist images from your node.js application to your browser app.

here is a snippet of how you could achieve something like this with express.js:
```js
app.get('/mnist', (req, res) => {
    const dataset = req.query.dataset;
    const id = req.query.id;
    res.send(mnist[dataset][id]);
})
```

You could then fetch any image from your server by providing the right ip, port & queries

```sh
curl http://IP:PORT/mnist?dataset=train&id=34
```

**Comment by mtygesen** [comment]
Will try! thanks for the fast reply.
